global:
  pattern: industrial-edge

  options:
    useCSV: False
    syncPolicy: Automatic
    installPlanApproval: Automatic

  git:
    provider: github.com
    account: rh-emea-sa-bot
    username: rh-emea-sa-bot
    email: rh.emea.sa.bot@gmail.com
    dev_revision: odf

  quay:
    provider: quay.io
    account: mmurakam+rh_emea_sa_bot

  datacenter:
    clustername: PLAINTEXT
    domain: PLAINTEXT

  edge:
    clustername: PLAINTEXT
    domain: PLAINTEXT

